# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
# triggered on master branch
- master

pool: SelfPool

# Pipelines -> Stages (qa, prod) -> Jobs -> Tasks (Steps)

jobs:
- job: Job1
  steps:
  # task 1
  - script: echo Job1 - Hello, world!
    displayName: 'Run a one-line script'

  # task 2
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

- job: Job2
  dependsOn: Job1
  steps:
  # task 1
  - script: echo Job2
    displayName: 'Run a one-line script'

- job: Job3
  dependsOn: Job2
  steps:
  # task 1
  - script: echo Job3
    displayName: 'Run a one-line script'

- job: Job4
  dependsOn:
  - Job2
  - Job3
  steps:
  # task 1
  - script: echo Job3
    displayName: 'Run a one-line script'