version: '3.2'
services:
  jenkins:
    image: jenkinsci/blueocean:latest
    privileged: true
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - ./jenkins_data:/var/jenkins_home
#      - /tmp/jenkins:/var/jenkins_home  #Remember that, the tmp directory is designed to be wiped on system reboot.
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/local/bin/docker
